### PR TITLE
Pull request to review the code for the responsive design project

### PR DESCRIPTION
**Pull request by Prabhakarzx**
### This is to request the code review for our project called Responsive Web design

**This webpage is the clone of _The Next Web_ site.**

In this project we've used three main files
- HTML(index.html)
- CSS(style.css)
- CSS(queries.css) for responsiveness on certain screen resolutions.

In this Project we've used **HTML and CSS**

### The above mentioned site is cloned for educational purpose only. All rights are reserved to its original owner(s).

**Thank You for taking your time to review our code.** :bouquet: 

**_Thanks!_**

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🛑

## Hello @Prabhakarzx and @tadeuasarro 👋. What an incredible project you have made 👌👏🧨! Killer README btw 💯!

### But before we can merge, let's look at some issues:

- Let's add the linear gradient backgrounds in the `top 3 articles`.

#### Clone
image

#### Original
image

- Let's change the text-color here 👇
image

*Remember to put the text-color property on the `a` tag, not on `li`.*

- Let's fix this in `latest news`.
image

- Same in `latest deals`.
image

- Add some space where I have marked red.
image

- Let's fix the `latest funding` to match the original.

#### Clone
image

#### Original
image


Your project is really amazing. Please apply the changes and request another review.

Happy coding 👨‍💻

**Comment by Prabhakarzx** [comment]
### Hi @tirthajyoti-ghosh,
**Greetings of the day**
### A very helpful insight and a wonderful and timely review indeed!
**Thank You so much for your time taken to review our code.**
### We're fixing the required changes. Thanks! :bouquet:

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team! 🖥️ 👀 ✨ 

- Excellent work positioning and resizing elements. 💯 
- Good choice of fonts 🔢 

## However, some changes are still required... 🧰 🔨 🔧 

- On Medium Display your page is missing the TNW logo on the navbar:

| Your version | Original page |
| --- | --- |
| image | image |

- On Small Display some of the images on the Latest Articles section appear stretched. Please fix this!

| Your version | Original Page |
| --- | --- |
| image | image |

- The text at the bottom of your footer wraps around. The footer text is supposed to remain on a single line for all Display sizes.

| Your version | Original Page |
| --- | --- |
| image | image |

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by Prabhakarzx** [comment]
### Hi @voscarmv!
**Greetings of the day!**
### Thanks for taking your time for the review. We really appreciate it.
**We've tried fixing it.**
_Hope, it is now up to the mark!_
### Thank You! :bouquet:

**Review by HADDADSOHAIB — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: 

### Hi @Prabhakarzx  and @tadeuasarro  :+1: 

### You did great with the project, it is very similar to the original. Good job

### However, I think the footer in mobile view need improvement:
- clone
Screenshot from 2020-07-04 11-24-41
- original
Screenshot from 2020-07-04 11-24-18
### Once done with the changes, ask for another code review.

**Comment by Prabhakarzx** [comment]
### Dear @HADDADSOHAIB 
**Greeting of the day!**
### Thanks for the review.
**We've fixed the issue.**
Thanks! :bouquet:

**Review by HADDADSOHAIB — APPROVED** [review]
### Status: Project Approved :+1: 

### Hi @Prabhakarzx  and @tadeuasarro    :hand: 

### You did great with the project, you implemented all changes required with the previous TSEs, you can go on and merge this branch into master.

**Comment by Prabhakarzx** [comment]
### Thank you so much @HADDADSOHAIB, @tirthajyoti-ghosh and @voscarmv for your efforts and timely reviews. :bouquet: 
**Your detailed and to the point reviews helped us to find out more technicalities and learn more. We fixed the things and learned at the same time.**
### Thank You So Much! :100: :bouquet:

**Pull request merged**
